version: "3.3"
volumes:
  db-data:
services:
  cli:
    build: cli
    # image: warr/php-cli
    # command: crond -f -l 8  #activate cronjob
    volumes:
      - ..:/workspaces/laravel
      - ./ssh:/home/user/.ssh
      - ./cli/cron:/etc/periodic/1min
  # database
  
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example456
      MYSQL_DATABASE: laravel-app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #simple database manager
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  
  # redis:
  #   image: redis:6.2-alpine